plugins {
    id 'java'
    id 'application'
}

group 'org.mcphackers'
version '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['src']
        }
    }
}
dependencies {
    implementation fileTree('../libraries') { include '**/*.jar' }
    implementation files("${rootDir}/jars/deobfuscated.jar")
}

application {
    mainClass = 'org.mcphackers.launchwrapper.Launch'
    applicationDefaultJvmArgs = [
        "-Djava.library.path=../libraries/natives",

        //debug server mode
        "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 -jar app.jar"
    ]
}

run {
    args = [
        //'--resourcesProxyPort', '11705',
        '--username', 'Parker_man',
        '--uuid', '-',
        '--session', '-',
        '--version', 'b1.7.3',
        '--gameDir', './game',
        '--assetsDir', './game/assets',
        '--assetIndex', 'b1.7',
        '--accessToken', '-',
        '--userProperties', '{}',
        '--userType', 'legacy',
        '--versionType', 'release',
        '--skinProxy', 'pre-b1.9-pre4'
    ]
}

